export const RoutesPath = {
  home: '/',
  menu: '/menu',
  menuDetail: (id: string) => `/menu/${id}`,
  checkout: '/checkout',
  orderConfirmation: (id: string) => `/orden-confirmacion/${id}`,
  reserve: '/reservas',
  contact: '/contacto',
  resenas: '/resenas',
  gestionReserva: '/gestion-reserva',
  adminLogin: '/admin-login',
  adminReservas: '/admin-reservas',
  adminOrdenes: '/admin-ordenes',
  adminDashboard: '/admin-dashboard',
  orderHistory: '/mis-pedidos',
  promociones: '/promociones',
  galeria: '/galeria',
  eventos: '/eventos',
  adminWhatsApp: '/admin-whatsapp',
  miPerfil: '/mi-perfil',
}
