export const RoutesPath = {
  home: '/',
  demo: '/demo',
  menu: '/menu',
  menuDetail: (id: string) => `/menu/${id}`,
  checkout: '/checkout',
  orderConfirmation: (id: string) => `/orden-confirmacion/${id}`,
  reserve: '/reservas',
  contact: '/contacto',
  resenas: '/resenas',
  gestionReserva: '/gestion-reserva',
  adminLogin: '/admin-login',
  adminReservas: '/admin-reservas',
  adminOrdenes: '/admin-ordenes',
  adminDashboard: '/admin-dashboard',
  orderHistory: '/mis-pedidos',
  promociones: '/promociones',
  galeria: '/galeria',
  eventos: '/eventos',
  adminWhatsApp: '/admin-whatsapp',
  adminClientes: '/admin-clientes',
  adminResenas: '/admin-resenas',
  adminCocina: '/admin-cocina',
  adminMesas: '/admin-mesas',
  miPerfil: '/mi-perfil',
  politicaPrivacidad: '/politica-privacidad',
  terminosCondiciones: '/terminos-condiciones',
  clientLogin: '/login',
  clientRegister: '/registro',
  clientPanel: '/mi-cuenta',
  orderTracking: (id: string) => `/seguimiento/${id}`,
  orderTrackingBase: '/seguimiento',
  aboutUs: '/nosotros',
  forgotPassword: '/recuperar-contrasena',
  adminPromociones: '/admin-promociones',
  adminInventario: '/admin-inventario',
  adminFinanzas: '/admin-finanzas',
  adminActividad: '/admin-actividad',
  adminProveedores: '/admin-proveedores',
  adminCompras: '/admin-compras',
  adminCaja: '/admin-caja',
  adminFacturacion: '/admin-facturacion',
  adminUsuarios: '/admin-usuarios',
  adminFidelizacion: '/admin-fidelizacion',
  adminEventos: '/admin-eventos',
  adminCatalogo: '/admin-catalogo',
}
